name: Pipeline de tests JUnit

on:
  push:
    branches:
      - main
      - TestBranch
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Build & Tests JUnit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Lancer les tests
        run: ./mvnw clean test --batch-mode

      # 5. Publier les résultats de tests (même si des tests échouent)
      - name: Publier les rapports de tests
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rapports-tests
          path: target/surefire-reports/
          retention-days: 10
